version: '3.3'

services:
  waterfurnace_aurora:
    container_name: waterfurnace_aurora
    build: 
      context: https://github.com/kevinclaycomb/waterfurnace_aurora.git#five_series_updates
      dockerfile: ./docker/Dockerfile
    image: kevinclaycomb/waterfurnace_aurora
    devices:
      - '/dev/ttyUSB0'
    environment:
      - TTY=/dev/ttyUSB0
      - MQTT=mqtt://localhost